version: '3'

services:
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - dev-redis-data:/data

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
    - dev-pg-data-main:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zero-protocol-labs

  db-tokenization:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - '5433:5432'
    volumes:
      - dev-pg-data-tokenization:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tokenization

  ganache-cli:
    image: trufflesuite/ganache-cli
    command: |
      ganache-cli \
        --db /data
        -m "chalk park staff buzz chair purchase wise oak receive avoid avoid home" \
        -l 8000000 \
        -e 1000000 \
        -a 40 \
        -h 0.0.0.0
    volumes:
      - dev-ganache-data:/data
    ports:
      - '127.0.0.1:8545:8545'

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:1025:1025'
      - '127.0.0.1:8025:8025'

volumes:
  dev-pg-data-main:
  dev-pg-data-tokenization:
  dev-ganache-data:
  dev-redis-data:
