-- CreateEnum
CREATE TYPE "LabelEnumType" AS ENUM ('EKOENERGY', 'EUROPEAN_GREEN', 'GREEN_POWER_AUSTRALIA', 'GREEN_E_ENERGY', 'HKN_NEU100', 'MILIEUKEUR', 'NATUREMADE', 'OK_POWER', 'RECS_INTERNATIONAL_QUALITY_STANDARD', 'RENEWABLEPLUS', 'TUV_SUD_MARK_EE01_EE02', 'ENERGIA_VERDE_100', 'BRA_MILJOVAL', 'GRUENER_STROM');

-- AlterTable
ALTER TABLE "Certificate" ADD COLUMN     "capacity" INTEGER,
ADD COLUMN     "commissioningDate" TIMESTAMP(3),
ADD COLUMN     "label" "LabelEnumType";
