name: Build & Test

on:
  pull_request:
    branches:
      - '*'
      - '!stage-test'

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  run-tests:
    runs-on: ubuntu-latest
    needs: cancel-previous

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16'

    - name: Set NPM_TOKEN
      run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

    - name: Install application
      run: yarn

    - name: Build application
      run: yarn build

